#!/usr/bin/env bash
# Install Nginx and set it up to serve a simple "Hello World!" page

apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
echo "Hello World!" > /var/www/html/index.html